framework:
    cache:
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            app.cache.redis:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
