# config/services.yaml

parameters:
    # You can define application parameters here if needed

services:
    # Default configuration for services
    _defaults:
        autowire: true        # Automatically inject dependencies
        autoconfigure: true   # Automatically register commands, event subscribers, etc.

    # Make classes in src/ available as services (except for listed exclusions)
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicit: Use Redis-backed app cache for your custom CacheService
    App\Service\CacheService:
        arguments:
            $cache: '@cache.app'

    # Explicit: Register a global API rate limit subscriber (uncomment if you add the subscriber class below)
    App\EventSubscriber\ApiRateLimitSubscriber:
        arguments:
            $apiLimiter: '@limiter.api_public'
        tags: [kernel.event_subscriber]

    # Add other service definitions below as needed
